from fastapi import APIRouter, Depends, HTTPException
from typing import List, Dict
from backend.services.task_stack_service import task_stack
from backend.services.holochain_service import holochain
from backend.services.attention_economy_service import attention_tokens

router = APIRouter(prefix="/tria", tags=["Tria Evolution"])

@router.get("/tasks", response_model=List[Dict])
async def get_tria_tasks():
    """
    Returns the current Stack of Tasks (monetized issues) generated by Global Tria.
    """
    return task_stack.get_available_tasks()

@router.post("/tasks/{task_id}/claim")
async def claim_tria_task(task_id: str, user_id: str):
    """
    Allows a developer to claim a task from the stack.
    """
    success = task_stack.claim_task(task_id, user_id)
    if not success:
        raise HTTPException(status_code=404, detail="Task not found or already in progress")
    return {"status": "success", "task_id": task_id}

@router.post("/snapshots")
async def receive_session_snapshot(snapshot: Dict):
    """
    Receives an evolutionary snapshot from Personal Tria (Offline mode).
    Triggers gap analysis, HoloChain hashing, and Attention Token rewards.
    """
    user_email = snapshot.get("user_email", "anonymous")
    
    # 1. HoloChain Hashing (Immutable sequence)
    new_block = holochain.add_snapshot(snapshot)
    
    # 2. Attention Economy (Reward calculation)
    reward_amount = attention_tokens.calculate_reward(snapshot)
    new_balance = attention_tokens.add_reward(user_email, reward_amount)
    
    # 3. Task Stack Gap Analysis (Evolutionary pressure)
    # Simulating gap analysis for now
    await task_stack.analyze_gap_and_generate_tasks([], [snapshot])
    
    return {
        "status": "snapshot_processed",
        "block_hash": new_block.hash,
        "reward": reward_amount,
        "balance": new_balance,
        "processed": True
    }
