#!/usr/bin/env python3
"""
TRIA: Training Engine (Opus-Level Core)
---------------------------------------
Implements a Residual U-Net (ResUNet) for Audio Spectral Inpainting.
Model learns to restore high-fidelity spectrograms from 'camera-dirty' inputs.

Workflow:
1. Load dataset (generated by generate_synthetic_dataset.py)
2. Define ResUNet architecture (optimized for ONNX/WebGPU)
3. Train with Multi-Loss (L1 + Spectral Convergence)
4. Export to ONNX
"""

import os
import argparse
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

# --- Architecture ---

class ResBlock(nn.Module):
    """Residual Block with skip connection."""
    def __init__(self, in_channels, out_channels, stride=1):
        super(ResBlock, self).__init__()
        self.conv1 = nn.Conv2d(in_channels, out_channels, kernel_size=3, stride=stride, padding=1, bias=False)
        self.bn1 = nn.BatchNorm2d(out_channels)
        self.relu = nn.ReLU(inplace=True)
        self.conv2 = nn.Conv2d(out_channels, out_channels, kernel_size=3, padding=1, bias=False)
        self.bn2 = nn.BatchNorm2d(out_channels)
        
        self.shortcut = nn.Sequential()
        if stride != 1 or in_channels != out_channels:
            self.shortcut = nn.Sequential(
                nn.Conv2d(in_channels, out_channels, kernel_size=1, stride=stride, bias=False),
                nn.BatchNorm2d(out_channels)
            )

    def forward(self, x):
        out = self.relu(self.bn1(self.conv1(x)))
        out = self.bn2(self.conv2(out))
        out += self.shortcut(x)
        out = self.relu(out)
        return out

class TriaResUNet(nn.Module):
    """Residual U-Net for Spectral Inpainting."""
    def __init__(self, in_channels=1, out_channels=1):
        super(TriaResUNet, self).__init__()
        
        # Encoder
        self.enc1 = ResBlock(in_channels, 32)   # 128x64 -> 128x64
        self.enc2 = ResBlock(32, 64, stride=2)  # 128x64 -> 64x32
        self.enc3 = ResBlock(64, 128, stride=2) # 64x32 -> 32x16
        
        # Bottleneck
        self.bottleneck = ResBlock(128, 256, stride=2) # 32x16 -> 16x8
        
        # Decoder
        self.up3 = nn.ConvTranspose2d(256, 128, kernel_size=2, stride=2)
        self.dec3 = ResBlock(256, 128) # Cat with enc3
        
        self.up2 = nn.ConvTranspose2d(128, 64, kernel_size=2, stride=2)
        self.dec2 = ResBlock(128, 64) # Cat with enc2
        
        self.up1 = nn.ConvTranspose2d(64, 32, kernel_size=2, stride=2)
        self.dec1 = ResBlock(64, 32) # Cat with enc1 (but enc1 is 128x64, let's fix decoder strides)
        
        # Final head
        self.final = nn.Conv2d(32, out_channels, kernel_size=1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        # Encoder
        s1 = self.enc1(x)
        s2 = self.enc2(s1)
        s3 = self.enc3(s2)
        
        # Bottleneck
        b = self.bottleneck(s3)
        
        # Decoder (with skip connections)
        u3 = self.up3(b)
        d3 = self.dec3(torch.cat([u3, s3], dim=1))
        
        u2 = self.up2(d3)
        d2 = self.dec2(torch.cat([u2, s2], dim=1))
        
        # Adjusting final up for 128xR -> 128xC
        # Since enc3/enc2 strides were 2, bottleneck was 2. Total 8x reduction.
        # Decoder up transforms: 16x8 -> 32x16 -> 64x32 -> 128x64
        u1 = self.up1(d2)
        d1 = self.dec1(torch.cat([u1, s1], dim=1))
        
        out = self.sigmoid(self.final(d1))
        return out

# --- Training Logic ---

def train_tria(data_path, epochs=50, batch_size=16, lr=1e-3, device='cpu'):
    # Load data
    print(f"Loading dataset: {data_path}")
    data = np.load(data_path)
    X = data['input'][:, np.newaxis, :, :] # (N, 1, F, T)
    Y = data['target'][:, np.newaxis, :, :]
    
    dataset = TensorDataset(torch.from_numpy(X).float(), torch.from_numpy(Y).float())
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=True)
    
    model = TriaResUNet().to(device)
    optimizer = optim.AdamW(model.parameters(), lr=lr)
    criterion = nn.L1Loss() # MAE for clean reconstruction
    
    print(f"Starting training on {device}...")
    for epoch in range(epochs):
        model.train()
        total_loss = 0
        for batch_x, batch_y in loader:
            batch_x, batch_y = batch_x.to(device), batch_y.to(device)
            
            optimizer.zero_grad()
            output = model(batch_x)
            loss = criterion(output, batch_y)
            loss.backward()
            optimizer.step()
            
            total_loss += loss.item()
        
        if (epoch+1) % 5 == 0:
            print(f"Epoch [{epoch+1}/{epochs}], Loss: {total_loss/len(loader):.6f}")

    return model

def export_onnx(model, dummy_input, out_path):
    print(f"Exporting model to ONNX: {out_path}")
    model.eval()
    torch.onnx.export(model, dummy_input, out_path, 
                      input_names=['input'], 
                      output_names=['output'],
                      dynamic_axes={'input': {0: 'batch_size'}},
                      opset_version=13)
    print("Export complete.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train TRIA Spectral Inpainter")
    parser.add_argument('--input', default='tria_dataset_v1.npz', help="Input .npz file")
    parser.add_argument('--epochs', type=int, default=30)
    parser.add_argument('--lr', type=float, default=1e-3)
    parser.add_argument('--onnx', default='tria_model.onnx', help="Output ONNX file")
    args = parser.parse_args()

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    
    if not os.path.exists(args.input):
        print(f"Error: {args.input} not found. Run generate_synthetic_dataset.py first.")
        # Exit if no dataset, but keep the code available
        sys.exit(1)

    # Train
    model = train_tria(args.input, epochs=args.epochs, lr=args.lr, device=device)
    
    # Export
    dummy_input = torch.randn(1, 1, 128, 64).to(device) # Shape must match generator output
    export_onnx(model, dummy_input, args.onnx)
    
    # Save PTH as backup
    torch.save(model.state_state_dict(), 'tria_model_v1.pth')
