name: Deploy to Hugging Face Space

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy_to_hf_space:
    runs-on: ubuntu-latest
    name: Trigger HF Space Rebuild
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger HF Space Restart
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN_SPACES_CONTROL }}
          SPACE_ID: "NeuroCoderZ/holograms-media"
        run: |
          set -e
          
          echo "Checking environment..."
          if [ -z "$HF_TOKEN" ]; then
            echo "Error: HF_TOKEN is not set! Please check GitHub repository secrets."
            exit 1
          fi
          echo "✓ HF_TOKEN is properly set"
          
          API_URL="https://huggingface.co/api/spaces/${SPACE_ID}/restart"
          echo "Attempting to trigger restart for ${SPACE_ID}"
          echo "Using API endpoint: ${API_URL}"
          
          echo "Sending POST request to Hugging Face API..."
          response_code=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
            -H "Authorization: Bearer $HF_TOKEN" \
            "${API_URL}")
            
          echo "API response status code: $response_code"
          
          if [ "$response_code" -eq 200 ] || [ "$response_code" -eq 202 ]; then
            echo "✓ Space restart command sent successfully (HTTP $response_code)"
          else
            echo "Error: Failed to trigger Space restart. HTTP status code: $response_code"
            echo "Fetching error details..."
            curl -X POST -H "Authorization: Bearer $HF_TOKEN" "${API_URL}"
            exit 1
          fi