name: Deploy to Hugging Face Space

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy_to_hf_space:
    runs-on: ubuntu-latest
    name: Trigger HF Space Rebuild
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install huggingface_hub
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade huggingface_hub

      - name: Trigger HF Space Rebuild
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN_SPACES_CONTROL }}
        run: |
          set -e # Немедленное прерывание при ошибках
          
          echo "Checking environment..."
          if [ -z "$HF_TOKEN" ]; then
            echo "Error: HF_TOKEN is not set! Please check GitHub repository secrets."
            exit 1
          fi
          echo "✓ HF_TOKEN is properly set"
          
          echo "Installing huggingface-cli..."
          which huggingface-cli || echo "Warning: huggingface-cli not found in PATH"
          
          echo "Logging in to Hugging Face..."
          huggingface-cli login --token "$HF_TOKEN"
          echo "✓ Login successful"
          
          echo "Triggering restart for NeuroCoderZ/holograms-media Space..."
          huggingface-cli space NeuroCoderZ/holograms-media --restart
          
          echo "✓ Space restart command sent successfully!"