name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # Запускается только при пуше в ветку main

jobs:
  build_and_deploy_prod:
    name: Build and Deploy to PROD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Firebase Hosting (PROD)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}'
          projectId: holograms-media
          target: prod # <--- КЛЮЧЕВОЕ ИЗМЕНЕНИЕ: Явно указываем таргет 'prod'

# --- Опционально: Деплой на DEV при пуше в другую ветку ---
#   build_and_deploy_dev:
#     name: Build and Deploy to DEV
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/develop' # Например, при пуше в ветку 'develop'
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Deploy to Firebase Hosting (DEV)
#         uses: FirebaseExtended/action-hosting-deploy@v0
#         with:
#           repoToken: '${{ secrets.GITHUB_TOKEN }}'
#           firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}'
#           projectId: holograms-media
#           target: dev # Указываем таргет 'dev'
