name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Deploy to PROD
        run: firebase deploy --only hosting:prod --token "${{ secrets.FIREBASE_TOKEN }}"

      - name: Deploy to DEV
        run: firebase deploy --only hosting:dev --token "${{ secrets.FIREBASE_TOKEN }}"