name: Keep IDX Workspace And Firebase Alive

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  ping-services:
    runs-on: ubuntu-latest
    steps:
      - name: Ping IDX Workspace
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.IDX_AUTH_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"command": "date"}' \
            "https://idx.google.com/api/v1/workspaces/hologramsmedia-91830644/execute"

      - name: Ping Firebase Hosting
        run: |
          curl -m 10 https://holograms.media/keep_alive || true
