name: Keep IDX Workspace Alive

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  ping-idx:
    runs-on: ubuntu-latest
    steps:
      - name: Ping IDX Workspace
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.IDX_AUTH_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"command": "date"}' \
            "https://idx.google.com/api/v1/workspaces/hologramsmedia-91830644/execute"
