name: Sync to Hugging Face Spaces

on:
  push:
    branches:
      - main # Запускать только при пуше в main
  workflow_dispatch: # Позволяет запускать вручную из GitHub Actions UI

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Trigger HF Space Rebuild

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Git # Необязательно для API-вызова, но не мешает
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Trigger Hugging Face Space Restart via API
        id: restart_space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN_SPACES_CONTROL }} # Используем твой секрет
          SPACE_ID: "NeuroCoderZ/holograms-media" # Твой Space ID
        run: |
          set -e
          echo "Проверяем наличие токена..."
          if [ -z "$HF_TOKEN" ]; then
            echo "Ошибка: HF_TOKEN не установлен! Проверьте секреты репозитория GitHub."
            exit 1
          fi
          echo "✓ HF_TOKEN установлен корректно."

          API_URL="https://huggingface.co/api/spaces/${SPACE_ID}/restart"
          echo "Попытка запустить перезапуск для Space ID: ${SPACE_ID}"
          echo "Используется API эндпоинт: ${API_URL}"

          echo "Отправляем POST запрос к Hugging Face API..."
          response_output_file=$(mktemp)
          response_code=$(curl -s -o "$response_output_file" -w "%{http_code}" -X POST \
            -H "Authorization: Bearer $HF_TOKEN" \
            "${API_URL}")

          echo "Статус код ответа API: $response_code"

          if [ "$response_code" -eq 200 ] || [ "$response_code" -eq 202 ]; then
            echo "✓ Команда перезапуска Space успешно отправлена (HTTP $response_code)"
            echo "::set-output name=restart_status::SUCCESS"
          else
            echo "Ошибка: Не удалось запустить перезапуск Space. HTTP статус код: $response_code"
            echo "Детали ошибки:"
            cat "$response_output_file"
            echo "::set-output name=restart_status::FAILURE"
            exit 1
          fi
          rm -f "$response_output_file"
