name: Sync to Hugging Face Spaces

on:
  push:
    branches:
      - main # Запускать только при пуше в main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Set up Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      # Этот шаг устанавливает URL для remote 'huggingface' с использованием токена.
      # Git будет использовать этот токен для аутентификации при push.
      # Имя пользователя (в данном случае 'user') здесь формальное,
      # Hugging Face аутентифицирует по токену.
      - name: Add Hugging Face Remote with Token
        run: |
          git remote add huggingface https://user:${{ secrets.HF_TOKEN_SPACES_CONTROL }}@huggingface.co/spaces/${{ github.repository_owner }}/${{ github.event.repository.name }}
          echo "Hugging Face remote added."

      - name: Push to Hugging Face
        run: |
          git push huggingface main --force
          echo "Successfully pushed to Hugging Face Spaces."
